In [1]:
import pandas as pd
import numpy as np

Converting the tsv file to csv format

In [4]:
import csv

tsv_file = '../Data/raw/gene_associations.tsv'
csv_file = '../Data/Raw/gene_associations.csv'

# Open the TSV file for reading and the CSV file for writing
with open(tsv_file, 'r', newline='') as tsvfile, open(csv_file, 'w', newline='') as csvfile:
    tsv_reader = csv.reader(tsvfile, delimiter='\t')
    csv_writer = csv.writer(csvfile)

    # Iterate over each row in the TSV file and write it to the CSV file
    for row in tsv_reader:
        csv_writer.writerow(row)

FileNotFoundError: [Errno 2] No such file or directory: '../Data/raw/gene_associations.tsv'

In [5]:
file = pd.read_csv('../Data/cleaned/gene_associations.csv')

In [6]:
file

,geneId,geneSymbol,DSI,DPI,PLI,protein_class_name,protein_class,NofDiseases,NofPmids
0,1,A1BG,0.700,0.538,4.991700e-09,Receptor,DTO_05007575,27,20
1,2,A2M,0.529,0.769,4.522900e-11,Enzyme modulator,DTO_05007584,147,145
2,3,A2MP1,NaN,NaN,NaN,NaN,NaN,1,1
3,9,NAT1,0.536,0.846,1.929400e-14,Enzyme,DTO_05007624,133,184
4,10,NAT2,0.451,0.885,3.274400e-06,Enzyme,DTO_05007624,311,627
...,...,...,...,...,...,...,...,...,...
21666,115482722,H3P33,0.736,0.346,NaN,NaN,NaN,19,15
21667,115482723,H3P40,0.506,0.846,NaN,NaN,NaN,175,202
21668,115561815,LNC-LBCS,0.890,0.077,NaN,NaN,NaN,3,1
21669,115804232,CEROX1,NaN,NaN,NaN,NaN,NaN,1,1
21670,115891964,MIR223HG,0.861,0.077,NaN,NaN,NaN,4,1

In [7]:
display(file)

,geneId,geneSymbol,DSI,DPI,PLI,protein_class_name,protein_class,NofDiseases,NofPmids
0,1,A1BG,0.700,0.538,4.991700e-09,Receptor,DTO_05007575,27,20
1,2,A2M,0.529,0.769,4.522900e-11,Enzyme modulator,DTO_05007584,147,145
2,3,A2MP1,NaN,NaN,NaN,NaN,NaN,1,1
3,9,NAT1,0.536,0.846,1.929400e-14,Enzyme,DTO_05007624,133,184
4,10,NAT2,0.451,0.885,3.274400e-06,Enzyme,DTO_05007624,311,627
...,...,...,...,...,...,...,...,...,...
21666,115482722,H3P33,0.736,0.346,NaN,NaN,NaN,19,15
21667,115482723,H3P40,0.506,0.846,NaN,NaN,NaN,175,202
21668,115561815,LNC-LBCS,0.890,0.077,NaN,NaN,NaN,3,1
21669,115804232,CEROX1,NaN,NaN,NaN,NaN,NaN,1,1
21670,115891964,MIR223HG,0.861,0.077,NaN,NaN,NaN,4,1

In [8]:
nan_indices = file.isna().any(axis=1)

In [9]:
file_cleaned = file[~nan_indices]

In [5]:
display.file_cleaned

AttributeError: 'function' object has no attribute 'file_cleaned'

In [11]:
missing_values = file.isnull().sum()

# Print the count of missing values
print(missing_values)

geneId                    0
geneSymbol                0
DSI                    1508
DPI                    1618
PLI                    5232
protein_class_name    13847
protein_class         13847
NofDiseases               0
NofPmids                  0
dtype: int64

In [12]:
file_clean = file_cleaned.dropna()

# Print the cleaned DataFrame
print(file_clean)

       geneId geneSymbol    DSI    DPI           PLI  \
0           1       A1BG  0.700  0.538  4.991700e-09
1           2        A2M  0.529  0.769  4.522900e-11
3           9       NAT1  0.536  0.846  1.929400e-14
4          10       NAT2  0.451  0.885  3.274400e-06
5          12   SERPINA3  0.486  0.846  8.833000e-14
...       ...        ...    ...    ...           ...
17011  317772     H2AC21  1.000  0.077  6.146700e-01
17016  319100      TAAR6  0.780  0.231  1.666800e-02
17023  326625       MMAB  0.695  0.538  4.129100e-03
17025  327657   SERPINA9  0.769  0.231  1.210600e-13
17032  337876      CHSY3  0.805  0.269  2.843900e-03

               protein_class_name protein_class  NofDiseases  NofPmids
0                        Receptor  DTO_05007575           27        20
1                Enzyme modulator  DTO_05007584          147       145
3                          Enzyme  DTO_05007624          133       184
4                          Enzyme  DTO_05007624          311       627
5                Enzyme modulator  DTO_05007584          229       300
...                           ...           ...          ...       ...
17011        Nucleic acid binding  DTO_05007557            1         0
17016  G-protein coupled receptor  DTO_02300001           12        18
17023                      Enzyme  DTO_05007624           46        45
17025            Enzyme modulator  DTO_05007584           14         5
17032                      Enzyme  DTO_05007624            8         6

[7419 rows x 9 columns]

In [13]:
file_clean.to_csv('cleaned_file.csv', index=False)